// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel_ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {

            // predict with default option.
            var modelOutput = MLModel.Predict(new MLModel.ModelInput() { Co=8.3f},10);
            Console.WriteLine(string.Join(",", modelOutput.Co));

            // predict next 5 periods
            modelOutput = MLModel.Predict(horizon: 5);
            Console.WriteLine(string.Join(",", modelOutput.Co));

            // update and predict model
            // TBD
        }
    }
}

